# Generated by Django 6.0.5 on 2026-05-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210906_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='discounted_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.FloatField(),
        ),
    ]
